#services:
#    # controllers are imported separately to make sure they're public
#    # and have a tag that allows actions to type-hint services
#    App\Action\:
#        resource: '../../src/Action/*'
#        public: true
#        autowire: true
#        autoconfigure: true
