twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '@SidusDataGrid/Form/bootstrap4.html.twig'
    globals:
        statusBadge:
            draft: warning
            rejected: danger
            validated: primary
            published: success
            unpublished: dark
