version: '3.4'

services:
    www:
        build: www
        working_dir: /var/www/current
        depends_on:
            - mysql
            - mailcatcher
        ports:
            - 80:80
        volumes:
            - ../:/var/www/current
            - ./www/nginx/sites-available/:/etc/nginx/sites-available/
            - ${SSH_AUTH_SOCK}:/ssh-agent
        environment:
            APP_ENV: dev
            APP_SECRET: adc3f69b4b8262565f7abb9513de7f36
            DATABASE_URL: 'mysql://symfony:symfony@mysql:3306/symfony'
            MAILER_URL: 'smtp://mailcatcher:1025'
            PHP_IDE_CONFIG: 'serverName=sidusadmindemo-cli'
        extra_hosts:
            - "host.docker.internal:172.17.0.1"

    mysql:
        image: mariadb
        ports:
            - 3306
        volumes:
            - volume_mysql:/var/lib/mysql
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony

    mailcatcher:
        image: zolweb/docker-mailcatcher:latest
        ports:
            - 1080:1080

volumes:
    volume_mysql:
        driver: local
